### ISSUE TITLE
Question 2-8 is an asymmetric range

### ISSUE THREAD

**Issue by AlexMGitHub** [altugbakan/accelerated-cpp-solutions#1]
In the edition of the text that I have, question 2-8 reads:

Write a program to generate the product of the numbers in the range [1, 10).

This is an asymmetric range and indicates the answer should be the product of number 1 through 9, which results in 362,880.

You have the range listed as [1, 10] which does result in the answer of 3,628,800 that you listed, but that range doesn't match the text in my printing of the book.

**Comment by altugbakan** [comment]
Hey Alex, thanks for your input.

It looks like you are right, would you like to fix it with a pull request?

**Comment by AlexMGitHub** [comment]
Done!  The pull request is linked to this issue.
